services:
  service_lojadejogos:
    container_name: container_lojadejogos
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - lojadejogos_network
    volumes:
      - .:/workspace/lojadejogos

networks:
  lojadejogos_network:
    driver: bridge
