services:
  service_lojadejogos:
    container_name: container_lojadejogos
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5433:8080"
    networks:
      - lojadejogos_network
    volumes:
      - .:/workspace/

networks:
  lojadejogos_network:
    driver: bridge
